# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOS Pokedex' do
pod "AFNetworking" ,"~> 3.0.0-beta.1"
pod 'pop', '~> 1.0'
pod "MagicalRecord"
pod 'JSONModel'
end

target 'iOS PokedexTests' do
pod 'OCMock' 

end
